sylius_mailer:
    emails:
        invoice_generated:
            subject: sylius.emails.invoice_generated.subject
            template: "@SyliusInvoicingPlugin/Resources/views/Invoice/Email/invoiceGenerated.html.twig"

knp_snappy:
    pdf:
        enabled: true

prooph_service_bus:
    event_buses:
        sylius_invoicing_event_bus: ~
    command_buses:
        sylius_invoicing_command_bus: ~

winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                sylius_invoicing_plugin_payment_complete_producer:
                    on: ['complete']
                    do: ['@Sylius\InvoicingPlugin\EventProducer\OrderPaymentPaidProducer', '__invoke']
                    args: ['object']

sylius_grid:
    templates:
        filter:
            invoice_channel: '@SyliusInvoicingPlugin/Grid/Filter/channel.html.twig'
    grids:
        sylius_invoicing_plugin_invoice:
            driver:
                name: doctrine/orm
                options:
                    class: 'expr:parameter("sylius_invoicing_plugin.model.invoice.class")'
            sorting:
                issuedAt: desc
            fields:
                number:
                    type: string
                    label: sylius_invoicing_plugin.ui.invoice_number
                    sortable: true
                orderNumber:
                    type: twig
                    label: sylius_invoicing_plugin.ui.order_number
                    options:
                        template: '@SyliusInvoicingPlugin/Invoice/Grid/Field/orderNumber.html.twig'
                    sortable: true
                issuedAt:
                    type: datetime
                    label: sylius_invoicing_plugin.ui.issued_at
                    sortable: true
                channel:
                    type: string
                    label: sylius.ui.channel
                    path: channelName
            filters:
                orderNumber:
                    type: string
                    label: sylius_invoicing_plugin.ui.order_number
                number:
                    type: string
                    label: sylius_invoicing_plugin.ui.invoice_number
                issuedAt:
                    type: date
                    label: sylius_invoicing_plugin.ui.issued_at
                channel:
                    type: invoice_channel
                    label: sylius.ui.channel
            actions:
                item:
                    show:
                        type: show
                    download:
                        type: default
                        label: sylius_invoicing_plugin.ui.download_invoice
                        icon: download
                        options:
                            link:
                                route: sylius_invoicing_plugin_admin_invoice_download
                                parameters:
                                    id: resource.id
